;;; cus-load.el --- automatically extracted custom dependencies
;;
;;; Code:

(put 'holidays 'custom-loads '("calendar"))
(put 'elp 'custom-loads '("elp"))
(put 'ffap 'custom-loads '("ffap"))
(put 'shell 'custom-loads '("shell" "terminal"))
(put 'nnmail 'custom-loads '("nnmail"))
(put 'shell-directories 'custom-loads '("shell"))
(put 'calendar-tex 'custom-loads '("cal-tex"))
(put 'gnus-article-emphasis 'custom-loads '("gnus-art"))
(put 'fortran 'custom-loads '("f90" "fortran"))
(put 'gnus-article-headers 'custom-loads '("gnus-art" "gnus-sum"))
(put 'f90 'custom-loads '("f90"))
(put 'ps-print-vertical 'custom-loads '("ps-print"))
(put 'supercite-hooks 'custom-loads '("supercite"))
(put 'chinese-calendar 'custom-loads '("cal-china"))
(put 'bookmark 'custom-loads '("bookmark"))
(put 'icon 'custom-loads '("icon"))
(put 'nnmail-procmail 'custom-loads '("nnmail"))
(put 'desktop 'custom-loads '("desktop"))
(put 'comint-completion 'custom-loads '("comint"))
(put 'gnus-score-kill 'custom-loads '("gnus-kill"))
(put 'remote-compile 'custom-loads '("rcompile"))
(put 'gnus-visual 'custom-loads '("earcon" "gnus-art" "gnus"))
(put 'dabbrev 'custom-loads '("dabbrev"))
(put 'completion 'custom-loads '("completion"))
(put 'cpp 'custom-loads '("cpp"))
(put 'gnus-score-expire 'custom-loads '("gnus-kill" "gnus-score"))
(put 'supercite-frames 'custom-loads '("supercite"))
(put 'windows 'custom-loads '("window"))
(put 'f90-indent 'custom-loads '("f90"))
(put 'gnus-summary-maneuvering 'custom-loads '("gnus-sum"))
(put 'gnus-start 'custom-loads '("gnus-group" "gnus-int" "gnus-start" "gnus-util" "gnus"))
(put 'gnus-extract-view 'custom-loads '("gnus-sum" "gnus-uu"))
(put 'dired-keys 'custom-loads '("dired-x"))
(put 'ediff-mult 'custom-loads '("ediff-mult"))
(put 'find-file 'custom-loads '("files"))
(put 'fortran-comment 'custom-loads '("fortran"))
(put 'viper 'custom-loads '("viper-cmd" "viper-ex" "viper-init" "viper-keym" "viper-macs" "viper-mous" "viper"))
(put 'widget-faces 'custom-loads '("wid-edit"))
(put 'resize-minibuffer 'custom-loads '("rsz-mini"))
(put 'gnus-various 'custom-loads '("gnus-sum"))
(put 'font-lock-highlighting-faces 'custom-loads '("font-lock"))
(put 'ange-ftp 'custom-loads '("ange-ftp"))
(put 'font-lock-extra-types 'custom-loads '("font-lock"))
(put 'minibuffer 'custom-loads '("complete"))
(put 'mouse-sel 'custom-loads '("mouse-sel"))
(put 'sort 'custom-loads '("sort"))
(put 'gnus-article-washing 'custom-loads '("gnus-art"))
(put 'mh-hook 'custom-loads '("mh-e"))
(put 'gnus-score-files 'custom-loads '("gnus-score"))
(put 'message-news 'custom-loads '("message"))
(put 'iswitchb 'custom-loads '("iswitchb"))
(put 'custom-buffer 'custom-loads '("cus-edit"))
(put 'tex-run 'custom-loads '("tex-mode"))
(put 'gnus-thread 'custom-loads '("gnus-sum"))
(put 'languages 'custom-loads '("cus-edit" "sgml-mode" "ada-mode" "fortran" "hideshow" "icon" "pascal" "prolog" "sh-script"))
(put 'ediff-ptch 'custom-loads '("ediff-ptch"))
(put 'jka-compr 'custom-loads '("jka-compr"))
(put 'development 'custom-loads '("cus-edit"))
(put 'ediff 'custom-loads '("ediff-diff" "ediff-init" "ediff-merg" "ediff-mult" "ediff-ptch" "ediff-wind" "ediff"))
(put 'gnus-treading 'custom-loads '("gnus-sum"))
(put 'strokes 'custom-loads '("strokes"))
(put 'mouse 'custom-loads '("mouse" "menu-bar" "avoid" "goto-addr" "mouse-sel" "strokes"))
(put 'nnmail-various 'custom-loads '("nnmail"))
(put 'extensions 'custom-loads '("iswitchb" "time-stamp" "wid-edit" "eldoc" "page-ext"))
(put 'appt 'custom-loads '("appt"))
(put 'rmail 'custom-loads '("rmail"))
(put 'message-various 'custom-loads '("message"))
(put 'term 'custom-loads '("terminal" "term"))
(put 'gnus-summary-exit 'custom-loads '("gnus-sum"))
(put 'news 'custom-loads '("supercite" "gnus" "message"))
(put 'ada 'custom-loads '("ada-mode"))
(put 'gnus 'custom-loads '("gnus-art" "gnus-async" "gnus-cache" "gnus-demon" "gnus-dup" "gnus-eform" "gnus-uu" "gnus-win" "gnus" "nnmail"))
(put 'calendar-hooks 'custom-loads '("calendar"))
(put 'mailalias 'custom-loads '("mailalias"))
(put 'frames 'custom-loads '("frame" "scroll-bar" "desktop" "ediff-wind" "imenu" "rsz-mini" "two-column"))
(put 'paren-showing 'custom-loads '("paren"))
(put 'display-time 'custom-loads '("time"))
(put 'reftex 'custom-loads '("reftex"))
(put 'makemode 'custom-loads '("make-mode"))
(put 'hexl 'custom-loads '("hexl"))
(put 'gnus-summary-visual 'custom-loads '("gnus-sum" "gnus"))
(put 'gnus-group-listing 'custom-loads '("gnus-group"))
(put 'rmail-reply 'custom-loads '("rmail"))
(put 'gnus-score 'custom-loads '("gnus-nocem" "gnus"))
(put 'gnus-group-select 'custom-loads '("gnus-sum"))
(put 'archive-lzh 'custom-loads '("arc-mode"))
(put 'message-buffers 'custom-loads '("message"))
(put 'docs 'custom-loads '("info" "makeinfo" "texinfo"))
(put 'indent 'custom-loads '("indent"))
(put 'enriched 'custom-loads '("enriched"))
(put 'gnus-threading 'custom-loads '("gnus-sum"))
(put 'rmail-headers 'custom-loads '("rmail"))
(put 'gnus-score-decay 'custom-loads '("gnus-score"))
(put 'help 'custom-loads '("cus-edit" "info" "man"))
(put 'widget-documentation 'custom-loads '("wid-edit"))
(put 'forms 'custom-loads '("forms"))
(put 'goto-address 'custom-loads '("goto-addr"))
(put 'gnus-nocem 'custom-loads '("gnus-nocem"))
(put 'paren-matching 'custom-loads '("simple" "paren"))
(put 'font-lock 'custom-loads '("font-lock"))
(put 'auto-save 'custom-loads '("files" "startup"))
(put 'gnus-cite 'custom-loads '("gnus-cite"))
(put 'gnus-demon 'custom-loads '("gnus-demon"))
(put 'gnus-message 'custom-loads '("message"))
(put 'mh-buffer 'custom-loads '("mh-utils"))
(put 'backup 'custom-loads '("files"))
(put 'matching 'custom-loads '("simple" "isearch" "replace" "bookmark" "completion" "ffap" "imenu"))
(put 'custom-faces 'custom-loads '("cus-edit"))
(put 'smtpmail 'custom-loads '("smtpmail"))
(put 'lisp-indent 'custom-loads '("cl-indent"))
(put 'tex 'custom-loads '("bibtex" "reftex" "tex-mode"))
(put 'imenu 'custom-loads '("imenu"))
(put 'server 'custom-loads '("server"))
(put 'archive 'custom-loads '("arc-mode"))
(put 'ps-print 'custom-loads '("ps-print"))
(put 'gnus-score-default 'custom-loads '("gnus-score" "gnus-sum"))
(put 'nnmail-duplicate 'custom-loads '("nnmail"))
(put 'custom-browse 'custom-loads '("cus-edit"))
(put 'partial-completion 'custom-loads '("complete"))
(put 'message-interface 'custom-loads '("message"))
(put 'pages 'custom-loads '("page-ext"))
(put 'diary 'custom-loads '("calendar" "diary-lib"))
(put 'custom-magic-faces 'custom-loads '("cus-edit"))
(put 'mh-compose 'custom-loads '("mh-comp"))
(put 'tex-view 'custom-loads '("tex-mode"))
(put 'nnmail-files 'custom-loads '("nnmail"))
(put 'gnus-edit-form 'custom-loads '("gnus-eform"))
(put 'ps-print-color 'custom-loads '("ps-print"))
(put 'emacs 'custom-loads '("cus-edit"))
(put 'comint 'custom-loads '("comint"))
(put 'isearch 'custom-loads '("isearch"))
(put 'abbrev 'custom-loads '("files" "cus-edit" "dabbrev" "hippie-exp"))
(put 'ediff-merge 'custom-loads '("ediff-merg"))
(put 'gnus-summary-mail 'custom-loads '("gnus-sum"))
(put 'apropos 'custom-loads '("apropos"))
(put 'tools 'custom-loads '("add-log" "compile" "diff" "ediff" "gud" "rcompile" "vc" "make-mode"))
(put 'gnus-topic 'custom-loads '("gnus-topic"))
(put 'sgml 'custom-loads '("sgml-mode"))
(put 'viper-mouse 'custom-loads '("viper-mous"))
(put 'ps-print-horizontal 'custom-loads '("ps-print"))
(put 'ps-print-face 'custom-loads '("ps-print"))
(put 'rmail-summary 'custom-loads '("rmail" "rmailsum"))
(put 'metamail 'custom-loads '("metamail"))
(put 'wp 'custom-loads '("cus-edit" "enriched" "lpr" "ps-print"))
(put 'gnus-summary-choose 'custom-loads '("gnus-sum"))
(put 'widget-browse 'custom-loads '("wid-browse"))
(put 'unix 'custom-loads '("gud" "rlogin" "shell" "term" "sh-script"))
(put 'diff 'custom-loads '("diff"))
(put 'external 'custom-loads '("cus-edit" "server"))
(put 'vc 'custom-loads '("files" "vc"))
(put 'pc-select 'custom-loads '("pc-select"))
(put 'i18n 'custom-loads '("cus-edit"))
(put 'sh 'custom-loads '("sh-script"))
(put 'message-headers 'custom-loads '("message"))
(put 'facemenu 'custom-loads '("facemenu"))
(put 'two-column 'custom-loads '("two-column"))
(put 'message-forwarding 'custom-loads '("message"))
(put 'ph 'custom-loads '("ph"))
(put 'message-faces 'custom-loads '("message"))
(put 'environment 'custom-loads '("cus-edit" "dired"))
(put 'custom-menu 'custom-loads '("cus-edit"))
(put 'comm 'custom-loads '("ph"))
(put 'mh 'custom-loads '("mh-comp" "mh-e" "mh-utils"))
(put 'gnus-article-mime 'custom-loads '("gnus-art" "gnus-sum"))
(put 'emulations 'custom-loads '("viper"))
(put 'compression 'custom-loads '("jka-compr"))
(put 'Help 'custom-loads '("apropos"))
(put 'nnmail-retrieve 'custom-loads '("nnmail"))
(put 'gnus-duplicate 'custom-loads '("gnus-dup"))
(put 'widgets 'custom-loads '("wid-browse" "wid-edit"))
(put 'abbrev-mode 'custom-loads '("abbrev" "cus-edit"))
(put 'earcon 'custom-loads '("earcon"))
(put 'hypermedia 'custom-loads '("browse-url" "goto-addr" "wid-edit" "metamail"))
(put 'prolog 'custom-loads '("prolog"))
(put 'info 'custom-loads '("info"))
(put 'texinfo 'custom-loads '("texinfo"))
(put 'dired-mark 'custom-loads '("dired"))
(put 'lazy-lock 'custom-loads '("lazy-lock"))
(put 'makeinfo 'custom-loads '("makeinfo"))
(put 'supercite-cite 'custom-loads '("supercite"))
(put 'save-place 'custom-loads '("saveplace"))
(put 'eldoc 'custom-loads '("eldoc"))
(put 'change-log 'custom-loads '("add-log"))
(put 'gnus-group-levels 'custom-loads '("gnus-group"))
(put 'files 'custom-loads '("files" "ange-ftp" "autorevert" "cus-edit"))
(put 'rmail-files 'custom-loads '("rmail"))
(put 'gnus-summary-format 'custom-loads '("gnus-sum"))
(put 'terminals 'custom-loads '("terminal"))
(put 'avoid 'custom-loads '("avoid"))
(put 'gnus-files 'custom-loads '("gnus" "nnmail"))
(put 'gnus-windows 'custom-loads '("gnus-win"))
(put 'gnus-article-buttons 'custom-loads '("gnus-art"))
(put 'reftex-label-support 'custom-loads '("reftex"))
(put 'gnus-summary 'custom-loads '("gnus-sum" "gnus"))
(put 'compilation 'custom-loads '("compile"))
(put 'gnus-article-hiding 'custom-loads '("gnus-art" "gnus-sum"))
(put 'lpr 'custom-loads '("lpr"))
(put 'ispell 'custom-loads '("ispell"))
(put 'auto-revert 'custom-loads '("autorevert"))
(put 'gnus-group 'custom-loads '("gnus-topic" "gnus"))
(put 'gnus-article-various 'custom-loads '("gnus-art" "gnus-sum"))
(put 'ediff-diff 'custom-loads '("ediff-diff"))
(put 'supercite 'custom-loads '("supercite"))
(put 'gnus-summary-marks 'custom-loads '("gnus-sum"))
(put 'bibtex-autokey 'custom-loads '("bibtex"))
(put 'editing-basics 'custom-loads '("simple" "files" "delsel" "pc-select"))
(put 'hscroll 'custom-loads '("hscroll"))
(put 'nnmail-expire 'custom-loads '("nnmail"))
(put 'gnus-article-saving 'custom-loads '("gnus-art"))
(put 'man 'custom-loads '("man"))
(put 'hippie-expand 'custom-loads '("hippie-exp"))
(put 'message-mail 'custom-loads '("message"))
(put 'modeline 'custom-loads '("time"))
(put 'archive-zoo 'custom-loads '("arc-mode"))
(put 'bibtex 'custom-loads '("bibtex"))
(put 'faces 'custom-loads '("faces" "facemenu" "cus-edit" "font-lock" "paren" "ps-print" "wid-edit" "make-mode" "gnus" "message"))
(put 'fill-comments 'custom-loads '("simple"))
(put 'gnus-summary-various 'custom-loads '("gnus-sum"))
(put 'applications 'custom-loads '("cus-edit" "uniquify"))
(put 'terminal 'custom-loads '("terminal"))
(put 'internal 'custom-loads '("startup" "cus-edit"))
(put 'lisp 'custom-loads '("lisp" "ielm" "cl-indent" "edebug" "elp" "scheme"))
(put 'local 'custom-loads '("calendar"))
(put 'rlogin 'custom-loads '("rlogin"))
(put 'archive-zip 'custom-loads '("arc-mode"))
(put 'gnus-extract-archive 'custom-loads '("gnus-uu"))
(put 'message 'custom-loads '("startup" "message"))
(put 'message-sending 'custom-loads '("message"))
(put 'archive-arc 'custom-loads '("arc-mode"))
(put 'rmail-output 'custom-loads '("rmailout"))
(put 'editing 'custom-loads '("simple" "indent" "paragraphs" "cus-edit" "outline" "hscroll" "nroff-mode"))
(put 'nroff 'custom-loads '("nroff-mode"))
(put 'executable 'custom-loads '("executable"))
(put 'gnus-score-adapt 'custom-loads '("gnus-score"))
(put 'message-insertion 'custom-loads '("message"))
(put 'gnus-extract-post 'custom-loads '("gnus-uu"))
(put 'pascal 'custom-loads '("pascal"))
(put 'rmail-retrieve 'custom-loads '("rmail"))
(put 'data 'custom-loads '("arc-mode" "forms" "hexl" "jka-compr" "saveplace" "sort" "time-stamp"))
(put 'mail 'custom-loads '("simple" "startup" "ph" "time" "mailalias" "metamail" "mh-e" "rmail" "smtpmail" "supercite" "gnus" "message"))
(put 'paren-blinking 'custom-loads '("simple"))
(put 'gnus-summary-sort 'custom-loads '("gnus-sum"))
(put 'fast-lock 'custom-loads '("fast-lock"))
(put 'customize 'custom-loads '("wid-edit" "cus-edit"))
(put 'dired 'custom-loads '("files" "dired-aux" "dired-x" "dired"))
(put 'fill 'custom-loads '("simple" "fill"))
(put 'ps-print-header 'custom-loads '("ps-print"))
(put 'outlines 'custom-loads '("outline"))
(put 'paragraphs 'custom-loads '("paragraphs"))
(put 'nnmail-split 'custom-loads '("nnmail"))
(put 'makefile 'custom-loads '("make-mode"))
(put 'supercite-attr 'custom-loads '("supercite"))
(put 'gnus-asynchronous 'custom-loads '("gnus-async"))
(put 'widget-button 'custom-loads '("wid-edit"))
(put 'uniquify 'custom-loads '("uniquify"))
(put 'ps-print-font 'custom-loads '("ps-print"))
(put 'dired-x 'custom-loads '("dired-x"))
(put 'tex-file 'custom-loads '("tex-mode"))
(put 'time-stamp 'custom-loads '("time-stamp"))
(put 'gnus-article-highlight 'custom-loads '("gnus-art"))
(put 'gud 'custom-loads '("gud"))
(put 'c-macro 'custom-loads '("cmacexp"))
(put 'gnus-extract 'custom-loads '("gnus" "gnus-uu"))
(put 'browse-url 'custom-loads '("browse-url"))
(put 'gnus-article 'custom-loads '("gnus-art" "gnus-cite"))
(put 'fortran-indent 'custom-loads '("fortran"))
(put 'edebug 'custom-loads '("edebug"))
(put 'scheme 'custom-loads '("scheme"))
(put 'gnus-group-foreign 'custom-loads '("gnus-group"))
(put 'initialization 'custom-loads '("startup"))
(put 'sh-script 'custom-loads '("sh-script"))
(put 'calendar 'custom-loads '("calendar" "solar"))
(put 'programming 'custom-loads '("cus-edit"))
(put 'hideshow 'custom-loads '("hideshow"))
(put 'C 'custom-loads '("cpp"))
(put 'mule 'custom-loads '("mule-cmds"))
(put 'c 'custom-loads '("cc-vars" "cmacexp"))
(put 'nnmail-prepare 'custom-loads '("nnmail"))
(put 'processes 'custom-loads '("comint" "compile" "cus-edit" "ispell" "rcompile" "rlogin" "shell" "term" "metamail" "executable"))
(put 'gnus-article-signature 'custom-loads '("gnus-art"))
(put 'viper-ex 'custom-loads '("viper-ex"))
(put 'ielm 'custom-loads '("ielm"))
(put 'killing 'custom-loads '("simple"))
(put 'gnus-group-various 'custom-loads '("gnus-group"))

(provide 'cus-load)

;;; cus-load.el ends here
